version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Asdf1234!"
      ACCEPT_EULA: "Y"
volumes:
  mssql-server-linux-data: